# Fetching the minified node image on apline linux
FROM node:slim

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /express-docker

# Installing dependencies
#COPY ./server/package.json /express-docker
COPY package.json .


# Installing dependencies
# RUN npm install

# Copying all the files in our project
COPY . .

# Starting our application
# CMD [ "node", "server.js" ]